name: SmartUI GitHub Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          with:
          ref: ${{ github.head_ref }}
          fetch-depth: 10

      - name: Get latest commit ID
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Commit Status URL
        run: |
          COMMIT_ID=${{ steps.commit.outputs.sha }}
          GITHUB_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${COMMIT_ID}"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV

      - name: Run Automation Script
        run: |
          echo "Running SmartUI CLI..."
          export LT_USERNAME=${{ vars.LT_USERNAME }}
          export LT_ACCESS_KEY=${{ vars.LT_KEY }}
          npm i @lambdatest/smartui-cli@latest
          npx smartui exec -- mvn test -D suite=sdk-cloud.xml
          npx smartui exec -- mvn test -D suite=sdk-cloud.xml