name: SmartUI GitHub Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ProjectName: [ github-integration-demo-cli ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 10

      - name: Get latest commit ID
        id: commit
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create GitHub Commit Status URL
        run: |
          COMMIT_ID=${{ steps.commit.outputs.sha }}
          GITHUB_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${COMMIT_ID}"
          echo "GITHUB_URL=$GITHUB_URL" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          npm i @lambdatest/smartui-cli@latest    

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest   

      - name: Run Automation Script SDK Cloud And Local
        run: |
          echo "Running SmartUI CLI..."
          export LT_USERNAME=${{ vars.LT_USERNAME }}
          export LT_ACCESS_KEY=${{ vars.LT_KEY }}
          export PROJECT=${{ matrix.ProjectName }}
          # npx smartui --config smartui-cli.json exec -- mvn -q test -D suite=sdk-cloud.xml
          export PROJECT_NAME=${{ matrix.ProjectName }}
          killall chrome
          npx smartui --config smartui-cli.json exec -- mvn -q test -D suite=sdk-local.xml
